<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:test="http://www.mulesoft.org/schema/mule/test"
      xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd

        http://www.mulesoft.org/schema/mule/test http://www.mulesoft.org/schema/mule/test/current/mule-test.xsd">

    <object name="objectStore"
            class="org.mule.runtime.api.store.SimpleMemoryObjectStore"/>

    <flow name="retryExhaustedCausedByUntypedError">
        <async>
            <try>
                <until-successful maxRetries="1" millisBetweenRetries="1000">
                    <test:processor throwException="true"/>
                </until-successful>
                <error-handler>
                    <on-error-continue/>
                </error-handler>
            </try>
        </async>
    </flow>

    <flow name="retryExhaustedCausedByConnectivityError">
        <try>
            <until-successful maxRetries="1" millisBetweenRetries="10">
                <test:processor throwException="true" exceptionToThrow="org.mule.runtime.api.connection.ConnectionException" exceptionText="Connection refused"/>
            </until-successful>
        </try>
    </flow>

    <flow name="retryExhaustedCausedByConnectivityErrorLogCheck">
        <until-successful maxRetries="1" millisBetweenRetries="10">
            <test:processor throwException="true" exceptionToThrow="org.mule.runtime.api.connection.ConnectionException" exceptionText="Connection refused"/>
        </until-successful>
        <error-handler>
            <test:on-error-check-log>
                <test:check-summary>
                    <test:summary-info key="Error type" value="MULE:RETRY_EXHAUSTED"/>
                    <test:summary-info key="Message" value="'until-successful' retries exhausted"/>
                    <test:summary-info key="Caused by" value="MULE:CONNECTIVITY: Connection refused"/>
                </test:check-summary>
            </test:on-error-check-log>
        </error-handler>
    </flow>

    <flow name="retryExhaustedCausedByNonConnectivityErrorLogCheck">
        <until-successful maxRetries="1" millisBetweenRetries="10">
            <test:processor throwException="true"/>
        </until-successful>
        <error-handler>
            <test:on-error-check-log>
                <test:check-summary>
                    <test:summary-info key="Error type" value="MULE:RETRY_EXHAUSTED"/>
                    <test:summary-info key="Message" value="'until-successful' retries exhausted"/>
                    <test:summary-info key="Caused by" value="MULE:UNKNOWN: Functional Test Service Exception"/>
                </test:check-summary>
            </test:on-error-check-log>
        </error-handler>
    </flow>

    <flow name="retryExhaustedCausedByMuleRuntimeErrorLogCheck">
        <until-successful maxRetries="1" millisBetweenRetries="10">
            <test:throw exception="org.mule.test.integration.routing.outbound.UntilSuccessfulRetryExhaustedTestCase.MuleRuntimeError" error="SECURITY"/>
        </until-successful>
        <error-handler>
            <test:on-error-check-log>
                <test:check-summary>
                    <test:summary-info key="Error type" value="MULE:RETRY_EXHAUSTED"/>
                    <test:summary-info key="Message" value="'until-successful' retries exhausted"/>
                    <test:summary-info key="Caused by" value="MULE:SECURITY: Mule runtime error"/>
                </test:check-summary>
            </test:on-error-check-log>
        </error-handler>
    </flow>

</mule>
